version: '3'

services:
    database:
      container_name: database
      image: postgres:13.4-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: study_django_rest
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./.docker/database:/docker-entrypoint-initdb.d
      ports:
        - 65432:5432

volumes:
  postgres_data: